# Use postgres/example user/password credentials
version: "3.1"

services:
  dbPostgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: archi
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
